Fix #1 mege any amount of pdfs
jpabeem/MergePDF pull request #4
Opened 2018-10-04 08:38 UTC by floatas

Fixes #1 moved some code around, created user controls. Added button which allows to add one more extra file, which allows to add any number of files.

2018-10-12 21:28 UTC, jpabeem commented
Thank you so much for your hard work! Sorry for the delay in accepting your work.

2018-10-12 21:48 UTC, jpabeem requested changes

2018-10-12 21:48 UTC, jpabeem commented on MergePDF/PdfSelectorControl.cs
> +                Text = $"Browse {Index} file",
I would say: "Browse file `{Index}`", resulting in "Browse file 1" & "Browse file 2".

2018-10-13 06:36 UTC, floatas commented
Glad that I could help, wanted to make some valuable pull request for hacktoberfest.

2018-10-13 12:08 UTC, jpabeem approved these changes

2018-10-13 12:13 UTC, merged